import Link from "next/link";
import { LegalShell } from "../components/legal-shell";

export const metadata = { title: "Privacy Policy | Pallos", description: "How Pallos collects, uses, and protects personal information.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() { return <LegalShell eyebrow="LEGAL" title="Privacy Policy" lead="What Pallos collects, why we use it, and the choices available to you.">
  <section><h2>Information we collect</h2><p>We may collect account and contact details; repository, scan, finding, and security records you choose to provide; details needed for paid work; payment status; support messages; and technical data such as browser, device, IP address, logs, and referring pages.</p><p>When you consent, Google Analytics and advertising technologies may collect usage, campaign, interaction, and device information. Never send passwords, private keys, payment-card details, or customer data by ordinary email.</p></section>
  <section><h2>How we use information</h2><p>We use information to provide and secure Pallos, run requested repository security checks, complete paid work, communicate with you, improve performance, prevent abuse, comply with law, and—with consent—measure usage and advertising or personalize advertising.</p></section>
  <section><h2>Connected services and code access</h2><p>GitHub access is read-only unless you separately approve implementation work. If you connect Supabase or another service, Pallos uses the access you authorize for the requested checks. Sensitive integration tokens are intended to be encrypted and access-limited.</p></section>
  <section><h2>Cookies, analytics, and advertising</h2><p>Necessary storage supports authentication, security, and your consent choice. Google Analytics and advertising or behavioral technologies are disabled until you choose the relevant category. You can change consent using Cookie settings. See our <Link href="/cookies">Cookie Policy</Link>.</p></section>
  <section><h2>Service providers and sharing</h2><p>We may share the minimum needed with providers that operate Pallos, including Vercel, Supabase, GitHub, Google after consent, and email or payment providers. We may disclose information when legally required, for security, or during a business transfer. We do not sell personal information.</p></section>
  <section><h2>Retention and security</h2><p>We retain information only as reasonably needed for these purposes, legal obligations, disputes, and security. We use reasonable safeguards, but no online system is completely secure.</p></section>
  <section><h2>Your choices and rights</h2><p>Depending on where you live, you may request access, correction, deletion, restriction, portability, or withdrawal of consent, and may object to certain processing. Email pallosagent@gmail.com. We may verify your identity.</p></section>
  <section><h2>Children, changes, and contact</h2><p>Pallos is not directed to children under 13. Updates will appear here with a new effective date. Send privacy questions to pallosagent@gmail.com.</p></section>
</LegalShell>; }
