import { LegalShell } from "../components/legal-shell";

export const metadata = { title: "Terms of Service | Pallos Agent", description: "Terms for Pallos Agent and its paid implementation services.", alternates: { canonical: "/terms" } };

export default function TermsPage() { return <LegalShell eyebrow="LEGAL" title="Terms of Service" lead="Terms for using Pallos Agent and any paid review or implementation service.">
  <section><h2>Acceptance and eligibility</h2><p>By using Pallos, you agree to these terms and confirm you can enter a binding agreement. If you act for an organization, you confirm you have authority to bind it.</p></section>
  <section><h2>Authorized use only</h2><p>You may connect or test only repositories, websites, accounts, and systems you own or are explicitly authorized to test. You may not disrupt the service, evade limits, access another person’s data, or use results unlawfully.</p></section>
  <section><h2>What Pallos does—and does not prove</h2><p>Pallos is an early-stage security scanner and monitoring tool. Results may be incomplete or incorrect and are not a security certification, compliance determination, penetration test, or guarantee. You remain responsible for review, testing, backups, and deployment decisions.</p></section>
  <section><h2>$79 founding-client fix package</h2><p>Unless a written proposal says otherwise, this includes one review, a before-and-after summary, one revision, and up to three straightforward agreed fixes requiring no more than 90 minutes total implementation. Target delivery is 3–4 business days after payment and receipt of required information and access.</p><p>It excludes redesigns, new features, migrations, paid software, complex architecture changes, incident response, penetration testing, compliance certification, and work beyond these limits. Extra work requires a separate written quote.</p></section>
  <section><h2>Payment, refunds, and access</h2><p>Payment is due before work starts. We refund payment if we reject the project before starting or cannot deliver the agreed service. Once customized work begins, payment is nonrefundable except where law requires. Provide minimum access, use staging and backups where possible, and never email credentials. You must test and approve changes before production.</p></section>
  <section><h2>Ownership and feedback</h2><p>You retain your code and content. Pallos retains its product, methods, branding, and pre-existing materials. You grant the limited rights needed to perform your request. We may use feedback without restriction or compensation.</p></section>
  <section><h2>Availability</h2><p>We may change, suspend, or discontinue features and restrict access for misuse, security risk, or legal reasons. Beta features may change without notice.</p></section>
  <section><h2>Disclaimers and liability</h2><p>To the fullest extent allowed by law, services are provided “as is” and “as available,” without warranties. Pallos is not liable for indirect, incidental, special, consequential, or lost-profit damages. Total liability will not exceed what you paid for the service giving rise to the claim. Applicable legal rights remain.</p></section>
  <section><h2>Disputes and contact</h2><p>Contact pallosagent@gmail.com first so we can try to resolve a dispute informally. Virginia law governs these terms without overriding mandatory consumer protections where you live. Updates will show a new effective date.</p></section>
</LegalShell>; }
